// Trong file index.ts của thư mục assets/sn
export { default as sinhnhat1 } from "./sn1.JPG";
export { default as sinhnhat2 } from "./sn2.jpg";
export { default as sinhnhat3 } from "./sn3.JPG";
export { default as sinhnhat4 } from "./sn4.jpg";
export { default as sinhnhat5 } from "./sn5.jpg";
export { default as sinhnhat6 } from "./sn5.mov";
export { default as sinhnhat7 } from "./sn6.jpg";
export { default as sinhnhat8 } from "./sn6.mov";
export { default as sinhnhat9 } from "./sn8.JPG";
